version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: morales1991/api_yamdb_web:v2.1
    restart: always
    command: >
      sh -c 'python manage.py migrate &&
      gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000'
    ports:
      - '8000:8000'
    volumes: 
      - static:/app/static
    env_file:
      - ./.env
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'    
    volumes:
      - static:/app/static:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static:
