version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: morales1991/api_yamdb_web:v2.1
    restart: always
    command: >
      sh -c 'python manage.py migrate &&
      gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000'
    volumes: 
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
  
  nginx:
    image: nginx:1.19.9
    restart: always
    ports:
      - '80:80'    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static:ro
      - media:/app/media:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
